EnvironmentInfo:
  platformName: Android
  platformVersion: 8.0.0
  deviceName: b7556c74
  browserName: chrome
  apk: E:/PycharmProjects/appium_auto/apk/dmbrand_v1.0.0.apk
  appPackage: com.elab.dmbrand
  appActivity: com.elab.dmbrand.splash.SplashActivity
  appium: 1.9.1
  automationName: Appium
  unicodeKeyboard: True
  resetKeyboard: True
  newCommandTimeout: 30
  noReset: True
  chromeOptions:
    androidProcess: com.tencent.mm:appbrand0
  html_report: E:/PycharmProjects/appium_auto/report/html
  xml_report: E:/PycharmProjects/appium_auto/report/xml

